export const DEMO_ORGANIZATION_ID = "demo_org_001"

export const DEMO_DATA = {
  orgChart: [
    {
      id: "1",
      name: "Sarah Chen",
      role: "Chief Executive Officer",
      department: "Executive",
      children: ["2", "3", "4"],
    },
    {
      id: "2",
      name: "Marcus Johnson",
      role: "VP Engineering",
      department: "Engineering",
      parent: "1",
      automationScore: 0.85,
      children: ["5", "6", "7"],
    },
    {
      id: "3",
      name: "Lisa Park",
      role: "VP Sales",
      department: "Sales",
      parent: "1",
      automationScore: 0.45,
      children: ["8", "9"],
    },
    {
      id: "4",
      name: "David Rodriguez",
      role: "Chief Financial Officer",
      department: "Finance",
      parent: "1",
      automationScore: 0.65,
      children: ["10", "11"],
    },
    {
      id: "5",
      name: "Alex Kumar",
      role: "Senior Software Engineer",
      department: "Engineering",
      parent: "2",
      automationScore: 0.72,
    },
    {
      id: "6",
      name: "Emma Wilson",
      role: "Senior Software Engineer",
      department: "Engineering",
      parent: "2",
      automationScore: 0.78,
    },
    {
      id: "7",
      name: "James O'Brien",
      role: "DevOps Lead",
      department: "Engineering",
      parent: "2",
      automationScore: 0.92,
      children: ["14"],
    },
    {
      id: "8",
      name: "Rachel Green",
      role: "Sales Manager",
      department: "Sales",
      parent: "3",
      automationScore: 0.38,
      children: ["12"],
    },
    {
      id: "9",
      name: "Tom Anderson",
      role: "Sales Manager",
      department: "Sales",
      parent: "3",
      automationScore: 0.42,
      children: ["13"],
    },
    {
      id: "10",
      name: "Priya Patel",
      role: "Finance Manager",
      department: "Finance",
      parent: "4",
      automationScore: 0.55,
    },
    {
      id: "11",
      name: "Michael Zhang",
      role: "Finance Coordinator",
      department: "Finance",
      parent: "4",
      automationScore: 0.88,
    },
    {
      id: "12",
      name: "Jennifer Lee",
      role: "Account Executive",
      department: "Sales",
      parent: "8",
      automationScore: 0.35,
    },
    {
      id: "13",
      name: "Chris Martinez",
      role: "Account Executive",
      department: "Sales",
      parent: "9",
      automationScore: 0.37,
    },
    {
      id: "14",
      name: "Sofia Duran",
      role: "Infrastructure Specialist",
      department: "Engineering",
      parent: "7",
      automationScore: 0.89,
    },
  ],
  metrics: {
    redundantRoles: 3,
    automationPotential: 45,
    approvalChainRedundancy: 2,
    potentialCostSavings: "$287K/year",
    recommendations: [
      {
        id: "rec-1",
        title: "Consolidate Finance Coordination Role",
        impact: "high" as const,
        description:
          "Michael Zhang's finance coordinator role can be 88% automated with AI-driven financial management tools. Estimated annual savings: $125K. Impact: Frees up capacity for strategic finance initiatives.",
      },
      {
        id: "rec-2",
        title: "Eliminate Redundant Sales Approval Process",
        impact: "high" as const,
        description:
          "Current sales approval chain has 2 redundant sign-offs (Manager + Director + Finance). Can be reduced to single manager approval using automated rules. Reduces sales cycle time by 40%.",
      },
      {
        id: "rec-3",
        title: "Automate DevOps Routine Tasks",
        impact: "medium" as const,
        description:
          "James O'Brien and Sofia Duran spend 60%+ time on repetitive infrastructure tasks. Implement IaC automation to handle 65% of current workload. Allows focus on strategic infrastructure planning.",
      },
      {
        id: "rec-4",
        title: "Merge Sales Manager Roles",
        impact: "medium" as const,
        description:
          "Rachel Green and Tom Anderson have overlapping responsibilities across different regions. Can be consolidated into single role managing both regions with improved efficiency.",
      },
      {
        id: "rec-5",
        title: "Implement Account Executive AI Assistant",
        impact: "medium" as const,
        description:
          "Jennifer and Chris spend 50% on administrative tasks (prospecting, data entry, follow-ups). AI assistant can handle lead qualification and CRM management automatically.",
      },
      {
        id: "rec-6",
        title: "Streamline Engineering Team Structure",
        impact: "low" as const,
        description:
          "Review shared responsibilities between Alex and Emma. Opportunity to specialize skill sets and reduce context switching. Estimated 15% efficiency improvement.",
      },
    ],
  },
  relationshipMap: {
    "1": ["2", "3", "4"],
    "2": ["5", "6", "7"],
    "3": ["8", "9"],
    "4": ["10", "11"],
    "8": ["12"],
    "9": ["13"],
    "7": ["14"],
  },
}
